# This is a basic workflow to help you get started with Actions

name: Discord
on:
  workflow_dispatch:

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Actions Status Discord
        uses: sarisia/actions-status-discord@v1.13.1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Larzous - Discord Test"
          description: |
            Testy test 1
            test2
            IT WORKS!
